Repository lansuite/lansuite, pull requests merged in 2018-06, with the labels that each got.

#325 Added symfony/debug component to get more information about errors
  composer.json
  composer.lock
  index.php
Labels: bug

#326 Module "picgallery": Fix PHP Warning: mysqli_free_result() expects parameter 1 to be mysqli_result, null given
  modules/picgallery/hitlist.php
Labels: bug

#327 Fix "Warning: usort() expects parameter 2 to be a valid callback, function 'compare' not found or invalid function name"
  inc/Classes/Debug.php
Labels: bug

#328 Fix "Call to a member function get_tag_content() on null"
  modules/install/ls_conf.php
Labels: bug

#329 Make $link argument of Display::FetchIcon optional
  inc/Classes/Display.php
Labels: bug

#330 Fix "Warning: mysqli_num_rows() expects parameter 1 to be mysqli_result, array given"
  modules/foodcenter/Classes/Category.php
  modules/foodcenter/Classes/Supplier.php
Labels: bug

#331 Fix "Call to a member function IncrementNumber() on null"
  modules/usrmgr/party.php
Labels: bug

#276 Paypal rework
  .travis.yml
  composer.json
  composer.lock
  modules/paypal/Classes/PayPal.php
  modules/paypal/Classes/PayPalItem.php
  modules/paypal/Functions/GetPriceDetails.php
  modules/paypal/Functions/SKUtoParty.php
  modules/paypal/Functions/SanitizeVal.php
  modules/paypal/createpayment.php
  modules/paypal/executepayment.php
  modules/paypal/mod_settings/config.xml
  modules/paypal/paying.php
  modules/paypal/paypal.php
Labels: enhancement, refactoring

#313 Added the documentation site based on facebooks Docusaurus
  .gitignore
  LICENSE
  README.md
  docs/development-api-docs.md
  docs/development-coding-style-guide.md
  docs/development-documentation.md
  docs/getting-started-configuration.md
  docs/getting-started-installation.md
  docs/getting-started-requirements.md
  docs/guides-upgrade.md
  website/blog/2018-06-01-documentation-launch.md
  website/core/Footer.js
  website/i18n/en.json
  website/package.json
  website/pages/en/credits.js
  website/pages/en/help.js
  website/pages/en/index.js
  website/pages/en/users.js
  website/sidebars.json
  website/siteConfig.js
  website/static/css/custom.css
  website/static/img/computer.svg
  website/static/img/docusaurus.svg
  website/static/img/favicon.png
  website/static/img/favicon/favicon.ico
  website/static/img/oss_logo.png
  website/static/img/projector.svg
  website/static/img/seats.svg
  website/static/img/tournament.svg
Labels: documentation

#334 Documentation: Add chapters on how to write and publish articles in the documentation
  docs/development-documentation.md
Labels: documentation

#336 Documentation: Add more context about the single configuration settings into the documentation for the Configuration chapter
  docs/getting-started-configuration.md
Labels: documentation
