Repository lansuite/lansuite, pull requests merged in 2019-01, with the labels that each got.

#385 usrmgr: Correctly quote strings to silence warnings.
  modules/usrmgr/Classes/UserManager.php
Labels: bug

#402 Issue #380: Drop support for PHP 7.0
  .travis.yml
Labels: enhancement

#386 mastersearch2: Fix PHP7.2 warning about count() on now non-countable objects
  modules/mastersearch2/templates/result_case.htm
Labels: bug

#399 Newsfeed: Fix XML encoding, handle HTTPS
  modules/news/Classes/News.php
Labels: bug, enhancement

#389 cron2: Allow database prefix variable in cron2 jobs
  modules/cron2/Classes/Cron2.php
  modules/cron2/mod_settings/db.xml
Labels: bug

#401 Add PHP 7.3 to the supported PHP versions in our builds
  .travis.yml
Labels: enhancement
