Repository lansuite/lansuite, pull requests merged in 2024-03, with the labels that each got.

#927 Impoved access to module DB update function
  CHANGELOG.md
  modules/install/Classes/Install.php
  modules/install/mod_cfg.php
Labels: enhancement, php

#844 Update jQuery & jQuery UI versions
  CHANGELOG.md
  ext_scripts/jquery-min.js
  ext_scripts/jquery-ui/LICENSE.txt
  ext_scripts/jquery-ui/images/ui-icons_444444_256x240.png
  ext_scripts/jquery-ui/images/ui-icons_555555_256x240.png
  ext_scripts/jquery-ui/images/ui-icons_777620_256x240.png
  ext_scripts/jquery-ui/images/ui-icons_777777_256x240.png
  ext_scripts/jquery-ui/images/ui-icons_cc0000_256x240.png
  ext_scripts/jquery-ui/images/ui-icons_ffffff_256x240.png
  ext_scripts/jquery-ui/jquery-ui.custom.min.js
  ext_scripts/jquery-ui/jquery-ui.min.css
  ext_scripts/jquery-ui/jquery-ui.min.js
  ext_scripts/jquery-ui/jquery-ui.structure.min.css
  ext_scripts/jquery-ui/jquery-ui.theme.min.css
  ext_scripts/jquery-ui/smoothness/images/ui-bg_flat_0_aaaaaa_40x100.png
  ext_scripts/jquery-ui/smoothness/images/ui-bg_flat_75_ffffff_40x100.png
  ext_scripts/jquery-ui/smoothness/images/ui-bg_glass_55_fbf9ee_1x400.png
  ext_scripts/jquery-ui/smoothness/images/ui-bg_glass_65_ffffff_1x400.png
  ext_scripts/jquery-ui/smoothness/images/ui-bg_glass_75_dadada_1x400.png
  ext_scripts/jquery-ui/smoothness/images/ui-bg_glass_75_e6e6e6_1x400.png
  ext_scripts/jquery-ui/smoothness/images/ui-bg_glass_95_fef1ec_1x400.png
  ext_scripts/jquery-ui/smoothness/images/ui-bg_highlight-soft_75_cccccc_1x100.png
  ext_scripts/jquery-ui/smoothness/images/ui-icons_222222_256x240.png
  ext_scripts/jquery-ui/smoothness/images/ui-icons_2e83ff_256x240.png
  ext_scripts/jquery-ui/smoothness/images/ui-icons_454545_256x240.png
  ext_scripts/jquery-ui/smoothness/images/ui-icons_888888_256x240.png
  ext_scripts/jquery-ui/smoothness/images/ui-icons_cd0a0a_256x240.png
  ext_scripts/jquery-ui/smoothness/jquery-ui.custom.css
  inc/Classes/Framework.php
Labels: security issue, javascript

#926 924-fix/improve cronjob handling
  CHANGELOG.md
  modules/cron2/Classes/Cron2.php
  modules/cron2/mod_settings/db.xml
  modules/cron2/show.php
Labels: bug, refactoring, php, conflicts

#928 [tournament2] PHP Warning fixes for game type "Single-Elimination, 1 gegen 1"
  inc/Classes/Func.php
  modules/guestlist/guestlist.php
  modules/tournament2/Classes/Team.php
  modules/tournament2/Functions/WriteGame.php
  modules/tournament2/Functions/WritePairs.php
  modules/tournament2/Functions/WritePairs2.php
  modules/tournament2/details.php
  modules/tournament2/games.php
  modules/tournament2/generate_pairs.php
  modules/tournament2/join.php
  modules/tournament2/tree.php
Labels: conflicts

#929 [tournament2] Fix further warnings in game modes "Liga" and "Gruppenspiele + KO"
  modules/tournament2/Classes/Team.php
  modules/tournament2/Classes/TournamentFunction.php
  modules/tournament2/games.php
  modules/tournament2/join.php
  modules/tournament2/submit_result.php
  modules/tournament2/tree.php
  modules/tournament2/tree_frame.php
Labels: conflicts

#910 [Security] Add header `X-Frame-Options`, `Referrer-Policy` and `Strict-Transport-Security`
  CHANGELOG.md
  index.php
Labels: conflicts

#1031 [Masterdelete] Switch SQL statements to Prepared Statements API
  inc/Classes/MasterDelete.php
Labels: conflicts
